files:
  - source: /ComposeN-Zik/src/androidMain/res/values/strings.xml
    translation: /ComposeN-Zik/src/androidMain/res/values-%two_letters_code%/strings.xml
  - source: /docs/res/values/strings.xml
    translation: /docs/res/values-%two_letters_code%/strings.xml

