name: 💡 Feature request
description: Suggest an idea to help us improve N-Zik
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        ****
        ### 💡 READ BEFORE SUBMITTING 💡
        
        Thanks for taking the time to suggest an idea for N-Zik!
        In-depth details will help us understand your vision and implement it better.

  - type: checkboxes
    id: prerequisites
    attributes:
      label: 📝 Before submitting
      description: Please verify the following step before submitting your request.
      options:
        - label: I have checked for already existing feature requests.
          required: true

  - type: checkboxes
    id: impact-assessment
    attributes:
      label: 📊 Impact Assessment
      description: Would this feature benefit many users or is it a niche use case?
      options:
        - label: "This would benefit many users"
        - label: "This is for a specific/niche use case"

  - type: markdown
    attributes:
      value: |
        ****

  - type: textarea
    id: device-information
    attributes:
      label: 📱 Device Information (Optional)
      description: If this feature is specific to a certain platform (e.g., Android Auto, Android TV) or hardware, please specify it here.
      placeholder: |
        App version: 5.0.0-f Full
        Platform Version: Android X, Android Auto/Automotive X, ...
        Device: Smartphone Brand & Model, Car Brand & Model Year, ...
    validations:
      required: false

  - type: textarea
    id: problem-statement
    attributes:
      label: 🎯 Problem Statement
      description: What problem does this feature solve? What's your use case?
      placeholder: |
        I want to do '...' because '...', and currently I can only do '...'
    validations:
      required: true

  - type: textarea
    id: suggested-solution
    attributes:
      label: ✨ Description or Suggested Solution
      description: Describe the feature/solution you'd like. A clear and concise description of what you want to happen.
      placeholder: |
        Add a '...' button in the '...' menu to allow users to '...'
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: 🔄 Alternatives
      description: Describe alternatives you've considered. A clear and concise description of any alternative solutions or features you've considered.
      placeholder: |
        Currently, I have to '...' which is '...', or use another app to '...'
    validations:
      required: false

  - type: textarea
    id: related-links
    attributes:
      label: 🔗 Related Links & References (Optional)
      description: Add links to similar features in other apps, mockups, wireframes, or any other references that help understand this feature request.
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ****
