name: Build & Sign Full Flavor Only (TEST)

on:
  workflow_dispatch:

jobs:
  versioning:
    name: Extract version
    runs-on: ubuntu-latest
    outputs:
      code: ${{ steps.downstream.outputs.code }}
    steps:
      - uses: actions/checkout@v4.2.1
        with:
          submodules: true
      - name: Get downstream (local) version code
        id: downstream
        run: |
          echo "code=$(grep -E '^\s*versionCode\s*=' composeApp/build.gradle.kts | awk -F '= ' '{print $2}')" >> $GITHUB_OUTPUT

  build-full:
    needs: [versioning]
    name: Build full version
    runs-on: ubuntu-latest
    timeout-minutes: 60       # Prevent Github Action from terminating this workflow on first run

    steps:
      - uses: actions/checkout@v4.2.1
        with:
          submodules: true

      - name: Copy changelogs into res/raw
        # Job should be canceled if file doesn't exist
        run: cp "fastlane/metadata/android/en-US/changelogs/${{ needs.versioning.outputs.code }}.txt" "composeApp/src/androidMain/res/raw/release_notes.txt"

      - name: Setup Java 21
        uses: actions/setup-java@v4.7.1
        with:
          java-version: "21"
          distribution: "corretto"

      - name: Restore Gradle dependencies & build cache
        uses: actions/cache@v4.2.3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            ./build
            ./composeApp/build
          # Cache key has flavor's name to prevent override each other
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: gradle-${{ runner.os }}-

      - name: Build with Gradle
        run: ./gradlew assembleGithubFull

      - name: Upload artifacts for signing
        uses: actions/upload-artifact@v4.6.2
        with:
          name: unsigned-release
          path: |
            composeApp/build/outputs/apk/github/release/*.apk

  sign-apks:
    name: Sign all built APKs
    needs:
      - build-full
    runs-on: ubuntu-latest
  
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4.3.0
        with:
          path: upstream/unsigned
          merge-multiple: true
  
      - name: Sign APKs
        uses: Tlaster/android-sign@v1.2.2
        with:
          releaseDirectory: upstream/unsigned
  
          signingKeyBase64: "${{ secrets.RELEASE_KEYSTORE }}"
          keyStorePassword: "${{ secrets.RELEASE_KEYSTORE_PASSWD }}"
          alias: "${{ secrets.RELEASE_KEY_ALIAS }}"
          keyPassword: "${{ secrets.RELEASE_KEY_PASSWD }}"
  
          output: signed
        env:
          BUILD_TOOLS_VERSION: "34.0.0"
  
      - name: Remove trails     # remove "-signed"
        run: |
          for filename in signed/*.apk; do mv "$filename" "${filename//-signed}"; done
  
      - name: Upload for release
        uses: actions/upload-artifact@v4.6.2
        with:
          name: signed-apks
          path: signed/*.apk
