name: Build & Sign Full Flavor Only (TEST)

on:
  workflow_dispatch:

jobs:
  versioning:
    name: Extract version
    runs-on: ubuntu-latest
    outputs:
      code: ${{ steps.downstream.outputs.code }}
    steps:
      - uses: actions/checkout@v4.2.1
        with:
          submodules: true
      - name: Get downstream (local) version code
        id: downstream
        run: |
          echo "code=$(grep -E '^\s*versionCode\s*=' composeApp/build.gradle.kts | awk -F '= ' '{print $2}')" >> $GITHUB_OUTPUT

  build-full:
    needs: [versioning]
    name: Build Full APK
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4.2.1
        with:
          submodules: true
      - name: Setup Java 21
        uses: actions/setup-java@v4.7.1
        with:
          java-version: "21"
          distribution: "corretto"
      - name: Restore Gradle cache
        uses: actions/cache@v4.2.3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            ./build
            ./composeApp/build
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: gradle-${{ runner.os }}-
      - name: Copy changelogs into resources
        run: cp "fastlane/metadata/android/en-US/changelogs/${{ needs.versioning.outputs.code }}.txt" "composeApp/src/androidMain/res/raw/release_notes.txt"
      - name: Build full flavor APK
        run: ./gradlew assembleFull
      - name: Upload unsigned full APK
        uses: actions/upload-artifact@v4.6.2
        with:
          name: unsigned-full-apk
          path: composeApp/build/outputs/apk/full/*.apk

  sign-full:
    needs: [build-full]
    name: Sign Full APK with production key
    runs-on: ubuntu-latest
    steps:
      - name: Download unsigned full APK
        uses: actions/download-artifact@v4.3.0
        with:
          name: unsigned-full-apk
          path: unsigned
      - name: Decode keystore
        run: echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > my-release-key.jks
      - name: Sign full APK
        run: |
          mkdir signed
          apksigner sign \
            --ks my-release-key.jks \
            --ks-pass pass:${{ secrets.KEYSTORE_PASSWORD }} \
            --key-pass pass:${{ secrets.KEY_PASSWORD }} \
            --ks-key-alias ${{ secrets.KEY_ALIAS }} \
            --out signed/full.apk unsigned/*.apk
      - name: Upload signed full APK
        uses: actions/upload-artifact@v4.6.2
        with:
          name: signed-full-apk
          path: signed/full.apk
