name: Build and Sign Full APK (Test)

on:
  workflow_dispatch:

jobs:
  build-full:
    name: Build Full APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: corretto

      - name: Build full flavor APK
        run: ./gradlew assembleFull

      - name: Upload unsigned APK
        uses: actions/upload-artifact@v4
        with:
          name: unsigned-apk
          path: composeApp/build/outputs/apk/full/*.apk

  sign-full:
    needs: build-full
    runs-on: ubuntu-latest
    steps:
      - name: Download unsigned APK
        uses: actions/download-artifact@v4
        with:
          name: unsigned-apk
          path: unsigned

      - name: Decode keystore
        run: echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > my-release-key.jks

      - name: Sign full APK
        run: |
          mkdir signed
          apksigner sign \
            --ks my-release-key.jks \
            --ks-pass pass:${{ secrets.KEYSTORE_PASSWORD }} \
            --key-pass pass:${{ secrets.KEY_PASSWORD }} \
            --ks-key-alias ${{ secrets.KEY_ALIAS }} \
            --out signed/full.apk unsigned/*.apk

      - name: Upload signed APK
        uses: actions/upload-artifact@v4
        with:
          name: signed-apk
          path: signed/full.apk
