name: Automatic Cache Builder

on:
  push:
    paths:
      - '**/*.gradle*'
      - '**/gradle-wrapper.properties'
    tags-ignore:
      - '**'

  schedule:
    - cron: '0 0 */2 * *'  # every 2 days at midnight UTC

  workflow_dispatch:

jobs:
  check-changes:
    name: Check for changes
    runs-on: ubuntu-latest
    outputs:
      changes_made: ${{ steps.detect-changes.outputs.changes_made }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 300
          submodules: true

      - name: Detect changes in last 48 hours
        id: detect-changes
        run: |
          CHANGES_MADE=false
          if \
            git log --since="48 hours ago" --name-only --pretty=format: | grep -q "^composeApp/src/androidMain/" || \
            git log --since="48 hours ago" --name-only --pretty=format: | grep -q "^composeApp/src/commonMain/" || \
            git log --since="48 hours ago" --name-only --pretty=format: | grep -q "^.*\.gradle.*" || \
            git log --since="48 hours ago" --name-only --pretty=format: | grep -q "^gradle-wrapper.properties"; then

            CHANGES_MADE=true
          fi
          echo "changes_made=$CHANGES_MADE" >> $GITHUB_OUTPUT

  build-cache:
    needs: check-changes
    if: needs.check-changes.outputs.changes_made == 'true'
    name: Build cache for all flavors
    runs-on: ubuntu-latest
    timeout-minutes: 90
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup JDK 21
        uses: actions/setup-java@v4.7.1
        with:
          distribution: 'corretto'
          java-version: '21'

      - name: Create fake release-notes.txt
        run: touch composeApp/src/androidMain/res/raw/release_notes.txt

      - name: Cache Gradle dependencies & build cache
        uses: actions/cache@v4.2.3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            ./build
            ./composeApp/build
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: gradle-${{ runner.os }}-

      - name: Build Minified flavor cache
        run: ./gradlew assembleMinified --build-cache --exclude-task packageMinified

      - name: Build Full flavor cache
        run: ./gradlew assembleFull --build-cache --exclude-task packageFull

      - name: Build Release flavor cache
        run: ./gradlew assembleRelease --build-cache --exclude-task packageRelease
