name: Notification to Discord

on:
  release:
    types: [published]

jobs:
  notify-beta:
    if: github.event.release.prerelease == true
    runs-on: ubuntu-latest
    steps:
      - name: 🧪 Beta Release Notification
        uses: SethCohen/github-releases-to-discord@v1.20.0
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          color: "16711680"
          username: "N-Zik Beta"
          avatar_url: "https://raw.githubusercontent.com/NEVARLeVrai/N-Zik/main/assets/discord/fallback_app.png"
          content: "⚠️ **||<@&1345079801324634195>|| BETA VERSION AVAILABLE!**\n\n🧪 Help us test the latest features!\n"
          footer_title: "N-Zik BETA • Testing & Feedback Needed"
          footer_icon_url: "https://raw.githubusercontent.com/NEVARLeVrai/N-Zik/main/assets/discord/fallback_app.png"
          footer_timestamp: true
          reduce_headings: true
          max_description: 2048

  notify-stable:
    if: github.event.release.prerelease == false
    runs-on: ubuntu-latest
    steps:
      - name: 🚀 Stable Release Notification
        uses: SethCohen/github-releases-to-discord@v1.20.0
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          color: "13632401"
          username: "N-Zik Stable"
          avatar_url: "https://raw.githubusercontent.com/NEVARLeVrai/N-Zik/main/assets/discord/fallback_app.png"
          content: "✨ **||<@&1345079801324634195>|| NEW STABLE RELEASE!**\n\n🚀 Download now!\n"
          footer_title: "N-Zik Stable • Made by the community, for the community"
          footer_icon_url: "https://raw.githubusercontent.com/NEVARLeVrai/N-Zik/main/assets/discord/fallback_app.png"
          footer_timestamp: true
          reduce_headings: true
          max_description: 2048
